### ISSUE TITLE
`PYTHONUTF8` breaks `ensurepip` under Python 3.7 on Windows

### ISSUE THREAD

**Issue by karrtikr** [brettcannon/WWBD#19]
Issue Type: <b>Bug</b>

Logs:
```
workspace: c:\Users\karraj\OneDrive - Microsoft\Desktop\folders\wwbd
interpreter: C:\Users\karraj\AppData\Local\Microsoft\WindowsApps\python3.7.exe
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\karraj\.vscode\extensions\brettcannon.wwbd-2022.0.1\python-src\__main__.py", line 9, in <module>
    main()
  File "c:\Users\karraj\.vscode\extensions\brettcannon.wwbd-2022.0.1\python-src\__main__.py", line 5, in main
    runpy.run_module("wwbd", alter_sys=True, run_name="__main__")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\karraj\.vscode\extensions\brettcannon.wwbd-2022.0.1\python-src\wwbd\__main__.py", line 31, in <module>
    main(sys.argv[1:])
  File "c:\Users\karraj\.vscode\extensions\brettcannon.wwbd-2022.0.1\python-src\wwbd\__main__.py", line 13, in main
    python_path = wwbd_venv.create(args.workspace)
  File "c:\Users\karraj\.vscode\extensions\brettcannon.wwbd-2022.0.1\python-src\wwbd\venv.py", line 24, in create
    venv.create(venv_path, with_pip=True, prompt=prompt)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\venv\__init__.py", line 390, in create
    builder.create(env_dir)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\venv\__init__.py", line 68, in create
    self._setup_pip(context)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\venv\__init__.py", line 288, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['c:\\Users\\karraj\\OneDrive - Microsoft\\Desktop\\folders\\wwbd\\.venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 101.
```

Extension version: 2022.0.1
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22518
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.63GB free)|
|Process Argv|--crash-reporter-id ba85916b-757f-4637-bf70-2eefba6645b4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

Pip is actually available as seen below:
![image](https://user-images.githubusercontent.com/13199757/166340577-7d5d6115-b4d2-406f-9381-f2cd2bd12f68.png)

**Comment by brettcannon** [comment]
This has nothing to do with the extension as that command is run by `venv` upon creating the environment (see the traceback).

https://github.com/brettcannon/WWBD/blob/fc0cd8b67f0226764b1cd9161493cd0452f3094a/python-src/wwbd/venv.py#L24

To replicate, you need to do `C:\Users\karraj\AppData\Local\Microsoft\WindowsApps\python3.7.exe -m venv .venv --prompt .` and see what happens. If that passes then can you call the Python code directly to try and replicate the issue?

**Comment by karrtikr** [comment]
Running `C:\Users\karraj\AppData\Local\Microsoft\WindowsApps\python3.7.exe -m venv .venv --prompt .` passes for me. I ran the following to call the python code directly, but strangely it passes as well:

```
C:/Users/karraj/AppData/Local/Microsoft/WindowsApps/python3.7.exe c:/Users/karraj/.vscode/extensions/brettcannon.wwbd-2022.0.1/python-src/__main__.py --workspace "C:\Users\karraj\OneDrive - Microsoft\Desktop\folders\wwbd"
```
It's probably not the right command which is being executed? I'll double check with the repository code.

**Comment by karrtikr** [comment]
So I debugged the extension and seems the issue is that extension sets https://github.com/brettcannon/WWBD/blob/fc0cd8b67f0226764b1cd9161493cd0452f3094a/src/extension.ts#L329

removing which fixes the error. I was able to reproduce this issue in terminal if that variable is set.

**Comment by brettcannon** [comment]
> removing which fixes the error.

Thanks for figuring that out!

The problem is that environment variable guarantees Python is communicating using UTF-8 over stdout to make sure there's no weird encoding problems for funky paths that get sent in the JSON output (see https://docs.python.org/3/using/windows.html#utf-8-mode for Windows details). Even with direct writing of UTF-8 to `stdout.buffer`, that doesn't guarantee any other weird output that we have seen from custom interpreter builds wouldn't print something that's incompatible with UTF-8 and thus break decoding. And I don't see https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html#child_processspawnsynccommand-args-options letting me specify something like `surrogateescape` to ignore encoding issues.

Does this happen with a newer version of Python? I don't see any shell being used in the `subprocess.check_output()` call in `venv`, so I'm wondering what is triggering the non-zero status code by forcing the use of UTF-8? I have had this work under Windows with Python 3.10, so I'm wondering if this is bug in pip or older Python versions?

**Comment by karrtikr** [comment]
(Had a offline discussion about rest of the stuff)
> Does this happen with a newer version of Python?

It does not happen with `3.9.12` windows store, was only able repro with `3.7.9`.

**Comment by brettcannon** [comment]
Offline, a good point was made by @karrtikr : if the Python extension isn't using `PYTHONUTF8` then the issues from encoding due to odd output from custom Python builds is going to be bigger than just this extension. And so in the name of wider compatibility it might make sense to skip worrying about encodings lining up in the subprocess communication.

I do want to test Python 3.8 to see if it also fails at this, but I will strongly consider just letting go of encoding correctness (for now).

**Comment by brettcannon** [comment]
Under CPython 3.8.12, it works fine, so this looks to be a Python 3.7 issue. Unfortunately 3.7 doesn't hit EOL until June 2023.
